// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwffoddjlibuqygncuag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3ZmZvZGRqbGlidXF5Z25jdWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTEzMTcsImV4cCI6MjA3MDU4NzMxN30.MLeTWNtegSrk68qfSBICKPiNLZiIxihVuNPN5VrS3vA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});